### PR TITLE
Fix documentation links.

### PR DESCRIPTION
**Pull request by tobias-richter**

### CODE REVIEW

**Comment by stefanseifert** [comment]
is this fix required? the link works for me without it (e.g. in gitlab).
and there are other links in the same style as well, eg. {{terraform#setup}}, that work for me as well.

**Comment by tobias-richter** [comment]
From my POV yes. My IDE (IntelliJ IDEA with Markdown Navigator) is marking this link as red / not resolvable / not working.
Leaving out the README.md and using it implicitely may work on Github but not on every GIT Server UI.

**Comment by stefanseifert** [comment]
then we should fix the other links as well?

**Comment by tobias-richter** [comment]
Of course, but i am not able to find any other link that is not correct (at the moment).
There is currently no search result for `/${symbol_pound}` or `/#`.

**Comment by stefanseifert** [comment]
i've fixed the two links to the terraform directory as well

**Comment by tobias-richter** [comment]
Oh, sorry, i did not find them.

**Pull request merged**
